version: '3.4'

services:
  vagrant_temp:
    container_name: ubuntu-vagrant
    #dns: 127.0.0.1
    network_mode: host
    #networks:
    #  - mynet
    # First build the image from the Dockerfile
    build:
    #  network: overlay
      # Change this to where you keep above Dockerfile
      context: .
    image: "ubuntu-vagrant:latest"
    volumes:
      - ~/.vagrant.d/boxes:/root/.vagrant.d/boxes

    # Then start a container from the just built image in privileged mode to finish what's left
    entrypoint: bash /do_vagrant_build.sh
    privileged: true
    #
    #networks:
    #mynet:
